### ISSUE TITLE
Bug in 0.17 alpha - Calling Websocket.send in Http.App.program's init doesn't work, the WebSocket message is never sent

### ISSUE THREAD

**Issue by knowthen** [elm-lang/websocket#3]
**Background:** I'm writing an app where a websocket message is sent on initial page load requesting data from the server

**Issue:** calling `WebSocket.send` in Http.App.program's `init` doesn't work.  Message seems to be lost.  

``` elm
init : (Model, Cmd Msg)
init =
  -- Looking at chrome dev tools, this string is never sent
  (Model "" "", WebSocket.send url "hello first time" )
```

**Speculation:** Seems to be either a timing issue waiting on the websocket to connect, or not properly queuing and sending the message after connected, or potentially some sort of runtime problem like this issue: https://github.com/elm-lang/core/issues/582

Calling `WebSocket.send` in `update` from a UI triggered `Msg` does work.

Here's the code: https://gist.github.com/knowthen/9348d4eda390139a82de91dc75167eab

Here's a quick demo showing the initial message isn't sent (on page load)
Then when I click the button, the message is sent and echoed back.

![alt text](https://media.giphy.com/media/26vUMqXR6wztwma5O/giphy.gif)

**Comment by ondras** [comment]
I can confirm this behavior; ran into the same issue.
