### ISSUE TITLE
Clarify there is currently no native websocket support in Elm

### ISSUE THREAD

**Issue by andys8** [elm-lang/websocket#30]
Quite often people ask in the elm slack how to use this package.
It would be nice if the `README.md` would explain and help people new to the language that there is currently (as of today with elm 0.19.1) no *native* websocket support. It might especially misleading that the `elm.json` [was updated](https://github.com/elm-lang/websocket/commit/1e9b6721e701fb69a9f08fcf2e8fe4c04a61c5f0).

It would also help to link to workarounds using ports like https://package.elm-lang.org/packages/bburdette/websocket/latest/

**Comment by evancz** [comment]
Updated the repo to point to the ports example in https://github.com/elm-community/js-integration-examples/

Also tried to explain what went wrong when trying to upgrade to 0.19 to cover the wider range of features that people were hoping to get from this API.
