### ISSUE TITLE
Bug in 0.17 alpha - Websocket.listen in Child Component loses the appropriate Msg Tagging erratic results

### ISSUE THREAD

**Issue by knowthen** [elm-lang/websocket#4]
When I call `WebSocket.listen` from within the outermost parent (Main.elm for example), thing seem to work as expected, however when I call `WebSocket.listen` on child components (Component.elm) I get erratic results.  In particular the Msg aren't properly tagged and pattern matching in the `update` function doesn't work properly..

In the later scenario (`WebSocket.listen` called from Component.elm), the first Message Received from the Server is properly returned, however subsequent messages lose the appropriate Msg tagging which screws up pattern matching and passing Component.Msg down...

Here's an example repo with a simple Parent & Child Component and a minimal Websocket Server (in nodejs).  
If you download the repo and follow steps in the README.md, you'll see what's happening.
https://github.com/knowthen/elm-websocket-bug-rpt

Here's a short video demo of the bug:
[![Bug](http://img.youtube.com/vi/L4M3aIhAQ-Y/0.jpg)](https://www.youtube.com/watch?v=L4M3aIhAQ-Y)

**Comment by knowthen** [comment]
Bwt, I tried to dig into the WebSocket code to find the bug... I see the Effects manager stuff you've eluded too, but I just don't know enough about how it's (Effects Manager etc) supposed to work to be much of a help.  Heck it might not be related to WebSocket, could be Platform related...

I imagine you're overwhelmed getting things together for the release, so not complaining... I just hate creating Bug reports without attempting to fix things myself or at least gaining better understanding what's going on... Just don't quite have enough info to work with yet :)

**Comment by ondras** [comment]
Confirming. Happens in my elm-irc library when tagging WebSocket messages as Irc messages.

**Comment by micktwomey** [comment]
I've a similar example which triggers a JS TypeError using a slight modification to the WebSocket example: https://gist.github.com/micktwomey/c1eb0f2354a5ab671f3e633c983b3b0e (the code is expecting a nested object with a ctor, instead it's a string).

(I wrote it before thinking to check for existing bugs, linking here in case a second example is useful.)

**Comment by evancz** [comment]
Thanks for the example! I updated the websocket package with its fixes. This one needed a change in core. I suspect there are a couple other things in core that'd be nice to fix, so that will come soon.
