### ISSUE TITLE
subMap in WebSocket module - dead code?

### ISSUE THREAD

**Issue by Janiczek** [elm-lang/websocket#6]
Is `subMap` a dead code, or does it serve eg. as a documentation for people trying to figure out effect managers?

Can it be deleted?

https://github.com/elm-lang/websocket/blob/master/src/WebSocket.elm#L102

**Comment by ThomasWeiser** [comment]
`subMap` is called when the app uses [`Sub.map`](http://package.elm-lang.org/packages/elm-lang/core/4.0.0/Platform-Sub#map) on the subscription. It is one of the functions needed in every `effect module` that deals with subscriptions.
